### ISSUE TITLE
Add more essences and some use for them 

### ISSUE THREAD

**Issue by adex720** [KingRealzYT/SwordsModForge#20]
Suggestion: Add more essences and some use for them

**Comment by jonatench** [comment]
essences indeed have a use, u use them to get into the light and dark dimension, there will also be more essences for light guardians and dark guardians for the light / dark sword and then the eclipse sword to be made.

**Comment by jonatench** [comment]
i just have to figure out how to make dimension beans cause im bad at json so yes

**Comment by adex720** [comment]
Aah ok

**Comment by jonatench** [comment]
yea, atm i've made the directory and file for the dimension just looking how to make the dimension
